### ISSUE TITLE
Issue with preview node

### ISSUE THREAD

**Issue by sheepkru** [AiSatan/node_wrangler_octane#53] opened 2024-01-06 15:01 UTC
Hello,
First of all thanks for this addon. Can't live without it!

I got version 1.4.1 but when I Ctrl+Shift+LMB i get the following message. Am aware this issue has been raised before. Tried installing previous versions but couldn't they don't work on my OctaneBlender v 28.7 installed.

![image](https://github.com/AiSatan/node_wrangler_octane/assets/155831231/0d70b0a7-b6a8-4067-b807-b79915950fb3)

Appreciate your help !

**Comment by AiSatan** [comment] 2024-01-06 15:25
Hi,
Yeah, this error hunts me for awhile now,
I will double check (today/tomorrow) and we will find solution for you as asap as possible, no worries! :)

Thank you :)

**Comment by AiSatan** [comment] 2024-01-07 16:13
Hi,

I'm using the same version but I cannot reproduce this behavior.

But, I made some small changes and made version just for you :)

Installation:
- Download and extract the node_wrangler.py file
- Remove old node_wrangler_octane (or/and disable default one)
- Restart Blender
- Install this node_wrangler.py file
- Just in case double check if version is 1.4.2 now in Blender
- Let me know :)

Be free to let me know here about the results and I'll close the issue or look for another solution for you, thanks!

[node_wrangler_octane.zip](https://github.com/AiSatan/node_wrangler_octane/files/13854105/node_wrangler_octane.zip)


omg, I wrote message and totally forget to send it, sorry for delay :)

**Comment by sheepkru** [comment] 2024-01-07 18:01
Heya, I just tried and it works if I created new materials.

![image](https://github.com/AiSatan/node_wrangler_octane/assets/155831231/2f79d686-f331-43f4-81d7-fbeecba78dad)


It shows the same error when I try it on materials created in previous versions (previous files). But it's fine - I can recreate them. 

Thanks so much! Really appreciate it =)

**Comment by AiSatan** [comment] 2024-01-08 03:46
Glad to hear that!

Thanks for letting me know, I will take a deeper look and see how can I improve this in the next updates.

If you face any new issues, please, feel free to open a new issue here, thank you and have a great year! :)

**Closed as completed by AiSatan** 2024-01-08 03:46 UTC
Labels: bug

**Comment by stevenjmotion** [comment] 2025-04-15 00:19
Hey, there,

I love your addon! Thanks for all the hard work and time you put in to keep this going! I’m having an issue using ctrl-click to preview a node in BO custom build 2025.1 which uses Blender 4.4. I’m getting a python error. Works ok in the previous versions. If you need the error message I can send that once I get home. Thanks again!

**Comment by AiSatan** [comment] 2025-04-15 02:58
Hi, @stevenjmotion 

Thank you, I'm glad you like it!

I've reproduced the issue, 

> RuntimeError: could not create instance of NODE_OT_nw_preview_node to call callback function 'invoke'
Error: Python: RuntimeError: could not create instance of NODE_OT_nw_preview_node to call callback function 'invoke'

I'll try to fix it as soon as possible. I've created new issue #62 where you can follow the progress and get notified when it's done. Thank you!
